### ISSUE TITLE
Json format for use with 3D Pose motion bert

### ISSUE THREAD

**Issue by CrisTTT** [Walter0807/MotionBERT#145]
Hi, I'm trying to inference motion bert in the wild. I am having issues with the JSON format that I should use for this. 

Below is the json format i am currently using. I can't find an example of a good JSON used for this in order to reformat it to the correct format.

{
    "annotations": [
        {
            "frame_id": 0,
            "keypoints": [
                256.0015869140625,
                455.171630859375,
                0.0,
                258.3621826171875,
                452.07177734375,
                0.0,
                264.28759765625,
                448.86700439453125,
                0.0,
                269.7962646484375,
                457.30731201171875,
                0.0,
                301.1651611328125,
                450.5689697265625,
                0.0,
                272.2452392578125,
                496.71942138671875,
                0.0,
                332.996337890625,
                473.644287109375,
                0.0,
                259.823974609375,
                527.5805053710938,
                0.0,
                360.90948486328125,
                497.08831787109375,
                0.0,
                254.77301025390625,
                496.04486083984375,
                0.0,
                375.521484375,
                638.1166381835938,
                0.0,
                320.78118896484375,
                609.2880249023438,
                0.0,
                365.06146240234375,
                593.7268676757812,
                0.0,
                323.9300537109375,
                698.5770874023438,
                0.0,
                357.780517578125,
                632.9181518554688,
                0.0,
                329.4959716796875,
                797.6443481445312,
                0.0,
                388.8597412109375,
                688.8500366210938,
                0.0
            ],
            "bbox": [
                0,
                0,
                478,
                850
            ]
        },
        {
            "frame_id": 1,
            "keypoints": [
                257.859619140625,
                454.60906982421875,
                0.0,
                259.45166015625,
                451.2744140625,
                0.0,
                266.6239013671875,
                447.96405029296875,
                0.0,
                270.135498046875,
                457.2606201171875,
                0.0,
                302.27679443359375,
                450.3916015625,
                0.0,
                273.5531005859375,
                496.06805419921875,
                0.0,
                333.98193359375,
                473.67254638671875,
                0.0,
                259.32861328125,
                526.0870971679688,
                0.0,
                361.90771484375,
                499.54449462890625,
                0.0,
                254.3492431640625,
                494.46270751953125,
                0.0,
                381.62225341796875,
                648.5664672851562,
                0.0,
                320.60833740234375,
                609.2427368164062,
                0.0,
                364.91314697265625,
                594.4885864257812,
                0.0,
                324.10009765625,
                698.9760131835938,
                0.0,
                356.1573486328125,
                631.1774291992188,
                0.0,
                327.9652099609375,
                795.2775268554688,
                0.0,
                389.0799560546875,
                689.3659057617188,
                0.0
            ],
            "bbox": [
                0,
                0,
                478,
                850
            ]
        },

**Comment by CrisTTT** [comment]
[vis_climb-trim.json](https://github.com/user-attachments/files/17467495/vis_climb-trim.json)
Here is an example of a JSON I want to use. The error I am encountering for:
python infer_wild.py --vid_path climb-trim.mp4 --json_path vis_climb-trim.mp4.json --out_path output_dump

is the following: 
Traceback (most recent call last):
  File "infer_wild.py", line 61, in <module>
    wild_dataset = WildDetDataset(opts.json_path, clip_len=opts.clip_len, scale_range=[1,1], focus=opts.focus)
  File "D:\motion\motionbert\lib\data\dataset_wild.py", line 95, in __init__
    self.vid_all = read_input(json_path, vid_size, scale_range, focus)
  File "D:\motion\motionbert\lib\data\dataset_wild.py", line 80, in read_input
    kpts_all = halpe2h36m(kpts_all)
  File "D:\motion\motionbert\lib\data\dataset_wild.py", line 51, in halpe2h36m
    raise ValueError("Input keypoints do not match the expected format. Expected at least 20 keypoints.")
ValueError: Input keypoints do not match the expected format. Expected at least 20 keypoints.
