### ISSUE TITLE
Cannot load checkpoint in docs/inference.MD

### ISSUE THREAD

**Issue by H4dr1en** [Walter0807/MotionBERT#24]
Hi, 

Thanks for the great work!

I tried to follow the instructions in `docs/inference.MD` and got the following error while loading the checkpoint:

<details>
  <summary>Error logs</summary>

```
(motionbert) H4dr1en@H4dr1en MotionBERT % /opt/miniconda3/envs/motionbert/bin/python /Users/H4dr1en/projects/MotionBERT/infer_wild_test.py
Loading checkpoint checkpoint/pose3d/FT_MB_lite_MB_ft_h36m_global_lite/best_epoch.bin
Traceback (most recent call last):
  File "/Users/H4dr1en/projects/MotionBERT/infer_wild_test.py", line 37, in <module>
    model_backbone.load_state_dict(checkpoint['model_pos'], strict=True)
  File "/opt/miniconda3/envs/motionbert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DSTformer:
        Missing key(s) in state_dict: "temp_embed", "pos_embed", "joints_embed.weight", "joints_embed.bias", "blocks_st.0.norm1_s.weight", "blocks_st.0.norm1_s.bias", "blocks_st.0.norm1_t.weight", "blocks_st.0.norm1_t.bias", "blocks_st.0.attn_s.proj.weight", "blocks_st.0.attn_s.proj.bias", "blocks_st.0.attn_s.qkv.weight", "blocks_st.0.attn_s.qkv.bias", "blocks_st.0.attn_t.proj.weight", "blocks_st.0.attn_t.proj.bias", "blocks_st.0.attn_t.qkv.weight", "blocks_st.0.attn_t.qkv.bias", "blocks_st.0.norm2_s.weight", "blocks_st.0.norm2_s.bias", "blocks_st.0.norm2_t.weight", "blocks_st.0.norm2_t.bias", "blocks_st.0.mlp_s.fc1.weight", "blocks_st.0.mlp_s.fc1.bias", "blocks_st.0.mlp_s.fc2.weight", "blocks_st.0.mlp_s.fc2.bias", "blocks_st.0.mlp_t.fc1.weight", "blocks_st.0.mlp_t.fc1.bias", "blocks_st.0.mlp_t.fc2.weight", "blocks_st.0.mlp_t.fc2.bias", "blocks_st.1.norm1_s.weight", "blocks_st.1.norm1_s.bias", "blocks_st.1.norm1_t.weight", "blocks_st.1.norm1_t.bias", "blocks_st.1.attn_s.proj.weight", "blocks_st.1.attn_s.proj.bias", "blocks_st.1.attn_s.qkv.weight", "blocks_st.1.attn_s.qkv.bias", "blocks_st.1.attn_t.proj.weight", "blocks_st.1.attn_t.proj.bias", "blocks_st.1.attn_t.qkv.weight", "blocks_st.1.attn_t.qkv.bias", "blocks_st.1.norm2_s.weight", "blocks_st.1.norm2_s.bias", "blocks_st.1.norm2_t.weight", "blocks_st.1.norm2_t.bias", "blocks_st.1.mlp_s.fc1.weight", "blocks_st.1.mlp_s.fc1.bias", "blocks_st.1.mlp_s.fc2.weight", "blocks_st.1.mlp_s.fc2.bias", "blocks_st.1.mlp_t.fc1.weight", "blocks_st.1.mlp_t.fc1.bias", "blocks_st.1.mlp_t.fc2.weight", "blocks_st.1.mlp_t.fc2.bias", "blocks_st.2.norm1_s.weight", "blocks_st.2.norm1_s.bias", "blocks_st.2.norm1_t.weight", "blocks_st.2.norm1_t.bias", "blocks_st.2.attn_s.proj.weight", "blocks_st.2.attn_s.proj.bias", "blocks_st.2.attn_s.qkv.weight", "blocks_st.2.attn_s.qkv.bias", "blocks_st.2.attn_t.proj.weight", "blocks_st.2.attn_t.proj.bias", "blocks_st.2.attn_t.qkv.weight", "blocks_st.2.attn_t.qkv.bias", "blocks_st.2.norm2_s.weight", "blocks_st.2.norm2_s.bias", "blocks_st.2.norm2_t.weight", "blocks_st.2.norm2_t.bias", "blocks_st.2.mlp_s.fc1.weight", "blocks_st.2.mlp_s.fc1.bias", "blocks_st.2.mlp_s.fc2.weight", "blocks_st.2.mlp_s.fc2.bias", "blocks_st.2.mlp_t.fc1.weight", "blocks_st.2.mlp_t.fc1.bias", "blocks_st.2.mlp_t.fc2.weight", "blocks_st.2.mlp_t.fc2.bias", "blocks_st.3.norm1_s.weight", "blocks_st.3.norm1_s.bias", "blocks_st.3.norm1_t.weight", "blocks_st.3.norm1_t.bias", "blocks_st.3.attn_s.proj.weight", "blocks_st.3.attn_s.proj.bias", "blocks_st.3.attn_s.qkv.weight", "blocks_st.3.attn_s.qkv.bias", "blocks_st.3.attn_t.proj.weight", "blocks_st.3.attn_t.proj.bias", "blocks_st.3.attn_t.qkv.weight", "blocks_st.3.attn_t.qkv.bias", "blocks_st.3.norm2_s.weight", "blocks_st.3.norm2_s.bias", "blocks_st.3.norm2_t.weight", "blocks_st.3.norm2_t.bias", "blocks_st.3.mlp_s.fc1.weight", "blocks_st.3.mlp_s.fc1.bias", "blocks_st.3.mlp_s.fc2.weight", "blocks_st.3.mlp_s.fc2.bias", "blocks_st.3.mlp_t.fc1.weight", "blocks_st.3.mlp_t.fc1.bias", "blocks_st.3.mlp_t.fc2.weight", "blocks_st.3.mlp_t.fc2.bias", "blocks_st.4.norm1_s.weight", "blocks_st.4.norm1_s.bias", "blocks_st.4.norm1_t.weight", "blocks_st.4.norm1_t.bias", "blocks_st.4.attn_s.proj.weight", "blocks_st.4.attn_s.proj.bias", "blocks_st.4.attn_s.qkv.weight", "blocks_st.4.attn_s.qkv.bias", "blocks_st.4.attn_t.proj.weight", "blocks_st.4.attn_t.proj.bias", "blocks_st.4.attn_t.qkv.weight", "blocks_st.4.attn_t.qkv.bias", "blocks_st.4.norm2_s.weight", "blocks_st.4.norm2_s.bias", "blocks_st.4.norm2_t.weight", "blocks_st.4.norm2_t.bias", "blocks_st.4.mlp_s.fc1.weight", "blocks_st.4.mlp_s.fc1.bias", "blocks_st.4.mlp_s.fc2.weight", "blocks_st.4.mlp_s.fc2.bias", "blocks_st.4.mlp_t.fc1.weight", "blocks_st.4.mlp_t.fc1.bias", "blocks_st.4.mlp_t.fc2.weight", "blocks_st.4.mlp_t.fc2.bias", "blocks_ts.0.norm1_s.weight", "blocks_ts.0.norm1_s.bias", "blocks_ts.0.norm1_t.weight", "blocks_ts.0.norm1_t.bias", "blocks_ts.0.attn_s.proj.weight", "blocks_ts.0.attn_s.proj.bias", "blocks_ts.0.attn_s.qkv.weight", "blocks_ts.0.attn_s.qkv.bias", "blocks_ts.0.attn_t.proj.weight", "blocks_ts.0.attn_t.proj.bias", "blocks_ts.0.attn_t.qkv.weight", "blocks_ts.0.attn_t.qkv.bias", "blocks_ts.0.norm2_s.weight", "blocks_ts.0.norm2_s.bias", "blocks_ts.0.norm2_t.weight", "blocks_ts.0.norm2_t.bias", "blocks_ts.0.mlp_s.fc1.weight", "blocks_ts.0.mlp_s.fc1.bias", "blocks_ts.0.mlp_s.fc2.weight", "blocks_ts.0.mlp_s.fc2.bias", "blocks_ts.0.mlp_t.fc1.weight", "blocks_ts.0.mlp_t.fc1.bias", "blocks_ts.0.mlp_t.fc2.weight", "blocks_ts.0.mlp_t.fc2.bias", "blocks_ts.1.norm1_s.weight", "blocks_ts.1.norm1_s.bias", "blocks_ts.1.norm1_t.weight", "blocks_ts.1.norm1_t.bias", "blocks_ts.1.attn_s.proj.weight", "blocks_ts.1.attn_s.proj.bias", "blocks_ts.1.attn_s.qkv.weight", "blocks_ts.1.attn_s.qkv.bias", "blocks_ts.1.attn_t.proj.weight", "blocks_ts.1.attn_t.proj.bias", "blocks_ts.1.attn_t.qkv.weight", "blocks_ts.1.attn_t.qkv.bias", "blocks_ts.1.norm2_s.weight", "blocks_ts.1.norm2_s.bias", "blocks_ts.1.norm2_t.weight", "blocks_ts.1.norm2_t.bias", "blocks_ts.1.mlp_s.fc1.weight", "blocks_ts.1.mlp_s.fc1.bias", "blocks_ts.1.mlp_s.fc2.weight", "blocks_ts.1.mlp_s.fc2.bias", "blocks_ts.1.mlp_t.fc1.weight", "blocks_ts.1.mlp_t.fc1.bias", "blocks_ts.1.mlp_t.fc2.weight", "blocks_ts.1.mlp_t.fc2.bias", "blocks_ts.2.norm1_s.weight", "blocks_ts.2.norm1_s.bias", "blocks_ts.2.norm1_t.weight", "blocks_ts.2.norm1_t.bias", "blocks_ts.2.attn_s.proj.weight", "blocks_ts.2.attn_s.proj.bias", "blocks_ts.2.attn_s.qkv.weight", "blocks_ts.2.attn_s.qkv.bias", "blocks_ts.2.attn_t.proj.weight", "blocks_ts.2.attn_t.proj.bias", "blocks_ts.2.attn_t.qkv.weight", "blocks_ts.2.attn_t.qkv.bias", "blocks_ts.2.norm2_s.weight", "blocks_ts.2.norm2_s.bias", "blocks_ts.2.norm2_t.weight", "blocks_ts.2.norm2_t.bias", "blocks_ts.2.mlp_s.fc1.weight", "blocks_ts.2.mlp_s.fc1.bias", "blocks_ts.2.mlp_s.fc2.weight", "blocks_ts.2.mlp_s.fc2.bias", "blocks_ts.2.mlp_t.fc1.weight", "blocks_ts.2.mlp_t.fc1.bias", "blocks_ts.2.mlp_t.fc2.weight", "blocks_ts.2.mlp_t.fc2.bias", "blocks_ts.3.norm1_s.weight", "blocks_ts.3.norm1_s.bias", "blocks_ts.3.norm1_t.weight", "blocks_ts.3.norm1_t.bias", "blocks_ts.3.attn_s.proj.weight", "blocks_ts.3.attn_s.proj.bias", "blocks_ts.3.attn_s.qkv.weight", "blocks_ts.3.attn_s.qkv.bias", "blocks_ts.3.attn_t.proj.weight", "blocks_ts.3.attn_t.proj.bias", "blocks_ts.3.attn_t.qkv.weight", "blocks_ts.3.attn_t.qkv.bias", "blocks_ts.3.norm2_s.weight", "blocks_ts.3.norm2_s.bias", "blocks_ts.3.norm2_t.weight", "blocks_ts.3.norm2_t.bias", "blocks_ts.3.mlp_s.fc1.weight", "blocks_ts.3.mlp_s.fc1.bias", "blocks_ts.3.mlp_s.fc2.weight", "blocks_ts.3.mlp_s.fc2.bias", "blocks_ts.3.mlp_t.fc1.weight", "blocks_ts.3.mlp_t.fc1.bias", "blocks_ts.3.mlp_t.fc2.weight", "blocks_ts.3.mlp_t.fc2.bias", "blocks_ts.4.norm1_s.weight", "blocks_ts.4.norm1_s.bias", "blocks_ts.4.norm1_t.weight", "blocks_ts.4.norm1_t.bias", "blocks_ts.4.attn_s.proj.weight", "blocks_ts.4.attn_s.proj.bias", "blocks_ts.4.attn_s.qkv.weight", "blocks_ts.4.attn_s.qkv.bias", "blocks_ts.4.attn_t.proj.weight", "blocks_ts.4.attn_t.proj.bias", "blocks_ts.4.attn_t.qkv.weight", "blocks_ts.4.attn_t.qkv.bias", "blocks_ts.4.norm2_s.weight", "blocks_ts.4.norm2_s.bias", "blocks_ts.4.norm2_t.weight", "blocks_ts.4.norm2_t.bias", "blocks_ts.4.mlp_s.fc1.weight", "blocks_ts.4.mlp_s.fc1.bias", "blocks_ts.4.mlp_s.fc2.weight", "blocks_ts.4.mlp_s.fc2.bias", "blocks_ts.4.mlp_t.fc1.weight", "blocks_ts.4.mlp_t.fc1.bias", "blocks_ts.4.mlp_t.fc2.weight", "blocks_ts.4.mlp_t.fc2.bias", "norm.weight", "norm.bias", "pre_logits.fc.weight", "pre_logits.fc.bias", "head.weight", "head.bias", "ts_attn.0.weight", "ts_attn.0.bias", "ts_attn.1.weight", "ts_attn.1.bias", "ts_attn.2.weight", "ts_attn.2.bias", "ts_attn.3.weight", "ts_attn.3.bias", "ts_attn.4.weight", "ts_attn.4.bias". 
        Unexpected key(s) in state_dict: "module.temp_embed", "module.pos_embed", "module.joints_embed.weight", "module.joints_embed.bias", "module.blocks_st.0.norm1_s.weight", "module.blocks_st.0.norm1_s.bias", "module.blocks_st.0.norm1_t.weight", "module.blocks_st.0.norm1_t.bias", "module.blocks_st.0.attn_s.proj.weight", "module.blocks_st.0.attn_s.proj.bias", "module.blocks_st.0.attn_s.qkv.weight", "module.blocks_st.0.attn_s.qkv.bias", "module.blocks_st.0.attn_t.proj.weight", "module.blocks_st.0.attn_t.proj.bias", "module.blocks_st.0.attn_t.qkv.weight", "module.blocks_st.0.attn_t.qkv.bias", "module.blocks_st.0.norm2_s.weight", "module.blocks_st.0.norm2_s.bias", "module.blocks_st.0.norm2_t.weight", "module.blocks_st.0.norm2_t.bias", "module.blocks_st.0.mlp_s.fc1.weight", "module.blocks_st.0.mlp_s.fc1.bias", "module.blocks_st.0.mlp_s.fc2.weight", "module.blocks_st.0.mlp_s.fc2.bias", "module.blocks_st.0.mlp_t.fc1.weight", "module.blocks_st.0.mlp_t.fc1.bias", "module.blocks_st.0.mlp_t.fc2.weight", "module.blocks_st.0.mlp_t.fc2.bias", "module.blocks_st.1.norm1_s.weight", "module.blocks_st.1.norm1_s.bias", "module.blocks_st.1.norm1_t.weight", "module.blocks_st.1.norm1_t.bias", "module.blocks_st.1.attn_s.proj.weight", "module.blocks_st.1.attn_s.proj.bias", "module.blocks_st.1.attn_s.qkv.weight", "module.blocks_st.1.attn_s.qkv.bias", "module.blocks_st.1.attn_t.proj.weight", "module.blocks_st.1.attn_t.proj.bias", "module.blocks_st.1.attn_t.qkv.weight", "module.blocks_st.1.attn_t.qkv.bias", "module.blocks_st.1.norm2_s.weight", "module.blocks_st.1.norm2_s.bias", "module.blocks_st.1.norm2_t.weight", "module.blocks_st.1.norm2_t.bias", "module.blocks_st.1.mlp_s.fc1.weight", "module.blocks_st.1.mlp_s.fc1.bias", "module.blocks_st.1.mlp_s.fc2.weight", "module.blocks_st.1.mlp_s.fc2.bias", "module.blocks_st.1.mlp_t.fc1.weight", "module.blocks_st.1.mlp_t.fc1.bias", "module.blocks_st.1.mlp_t.fc2.weight", "module.blocks_st.1.mlp_t.fc2.bias", "module.blocks_st.2.norm1_s.weight", "module.blocks_st.2.norm1_s.bias", "module.blocks_st.2.norm1_t.weight", "module.blocks_st.2.norm1_t.bias", "module.blocks_st.2.attn_s.proj.weight", "module.blocks_st.2.attn_s.proj.bias", "module.blocks_st.2.attn_s.qkv.weight", "module.blocks_st.2.attn_s.qkv.bias", "module.blocks_st.2.attn_t.proj.weight", "module.blocks_st.2.attn_t.proj.bias", "module.blocks_st.2.attn_t.qkv.weight", "module.blocks_st.2.attn_t.qkv.bias", "module.blocks_st.2.norm2_s.weight", "module.blocks_st.2.norm2_s.bias", "module.blocks_st.2.norm2_t.weight", "module.blocks_st.2.norm2_t.bias", "module.blocks_st.2.mlp_s.fc1.weight", "module.blocks_st.2.mlp_s.fc1.bias", "module.blocks_st.2.mlp_s.fc2.weight", "module.blocks_st.2.mlp_s.fc2.bias", "module.blocks_st.2.mlp_t.fc1.weight", "module.blocks_st.2.mlp_t.fc1.bias", "module.blocks_st.2.mlp_t.fc2.weight", "module.blocks_st.2.mlp_t.fc2.bias", "module.blocks_st.3.norm1_s.weight", "module.blocks_st.3.norm1_s.bias", "module.blocks_st.3.norm1_t.weight", "module.blocks_st.3.norm1_t.bias", "module.blocks_st.3.attn_s.proj.weight", "module.blocks_st.3.attn_s.proj.bias", "module.blocks_st.3.attn_s.qkv.weight", "module.blocks_st.3.attn_s.qkv.bias", "module.blocks_st.3.attn_t.proj.weight", "module.blocks_st.3.attn_t.proj.bias", "module.blocks_st.3.attn_t.qkv.weight", "module.blocks_st.3.attn_t.qkv.bias", "module.blocks_st.3.norm2_s.weight", "module.blocks_st.3.norm2_s.bias", "module.blocks_st.3.norm2_t.weight", "module.blocks_st.3.norm2_t.bias", "module.blocks_st.3.mlp_s.fc1.weight", "module.blocks_st.3.mlp_s.fc1.bias", "module.blocks_st.3.mlp_s.fc2.weight", "module.blocks_st.3.mlp_s.fc2.bias", "module.blocks_st.3.mlp_t.fc1.weight", "module.blocks_st.3.mlp_t.fc1.bias", "module.blocks_st.3.mlp_t.fc2.weight", "module.blocks_st.3.mlp_t.fc2.bias", "module.blocks_st.4.norm1_s.weight", "module.blocks_st.4.norm1_s.bias", "module.blocks_st.4.norm1_t.weight", "module.blocks_st.4.norm1_t.bias", "module.blocks_st.4.attn_s.proj.weight", "module.blocks_st.4.attn_s.proj.bias", "module.blocks_st.4.attn_s.qkv.weight", "module.blocks_st.4.attn_s.qkv.bias", "module.blocks_st.4.attn_t.proj.weight", "module.blocks_st.4.attn_t.proj.bias", "module.blocks_st.4.attn_t.qkv.weight", "module.blocks_st.4.attn_t.qkv.bias", "module.blocks_st.4.norm2_s.weight", "module.blocks_st.4.norm2_s.bias", "module.blocks_st.4.norm2_t.weight", "module.blocks_st.4.norm2_t.bias", "module.blocks_st.4.mlp_s.fc1.weight", "module.blocks_st.4.mlp_s.fc1.bias", "module.blocks_st.4.mlp_s.fc2.weight", "module.blocks_st.4.mlp_s.fc2.bias", "module.blocks_st.4.mlp_t.fc1.weight", "module.blocks_st.4.mlp_t.fc1.bias", "module.blocks_st.4.mlp_t.fc2.weight", "module.blocks_st.4.mlp_t.fc2.bias", "module.blocks_ts.0.norm1_s.weight", "module.blocks_ts.0.norm1_s.bias", "module.blocks_ts.0.norm1_t.weight", "module.blocks_ts.0.norm1_t.bias", "module.blocks_ts.0.attn_s.proj.weight", "module.blocks_ts.0.attn_s.proj.bias", "module.blocks_ts.0.attn_s.qkv.weight", "module.blocks_ts.0.attn_s.qkv.bias", "module.blocks_ts.0.attn_t.proj.weight", "module.blocks_ts.0.attn_t.proj.bias", "module.blocks_ts.0.attn_t.qkv.weight", "module.blocks_ts.0.attn_t.qkv.bias", "module.blocks_ts.0.norm2_s.weight", "module.blocks_ts.0.norm2_s.bias", "module.blocks_ts.0.norm2_t.weight", "module.blocks_ts.0.norm2_t.bias", "module.blocks_ts.0.mlp_s.fc1.weight", "module.blocks_ts.0.mlp_s.fc1.bias", "module.blocks_ts.0.mlp_s.fc2.weight", "module.blocks_ts.0.mlp_s.fc2.bias", "module.blocks_ts.0.mlp_t.fc1.weight", "module.blocks_ts.0.mlp_t.fc1.bias", "module.blocks_ts.0.mlp_t.fc2.weight", "module.blocks_ts.0.mlp_t.fc2.bias", "module.blocks_ts.1.norm1_s.weight", "module.blocks_ts.1.norm1_s.bias", "module.blocks_ts.1.norm1_t.weight", "module.blocks_ts.1.norm1_t.bias", "module.blocks_ts.1.attn_s.proj.weight", "module.blocks_ts.1.attn_s.proj.bias", "module.blocks_ts.1.attn_s.qkv.weight", "module.blocks_ts.1.attn_s.qkv.bias", "module.blocks_ts.1.attn_t.proj.weight", "module.blocks_ts.1.attn_t.proj.bias", "module.blocks_ts.1.attn_t.qkv.weight", "module.blocks_ts.1.attn_t.qkv.bias", "module.blocks_ts.1.norm2_s.weight", "module.blocks_ts.1.norm2_s.bias", "module.blocks_ts.1.norm2_t.weight", "module.blocks_ts.1.norm2_t.bias", "module.blocks_ts.1.mlp_s.fc1.weight", "module.blocks_ts.1.mlp_s.fc1.bias", "module.blocks_ts.1.mlp_s.fc2.weight", "module.blocks_ts.1.mlp_s.fc2.bias", "module.blocks_ts.1.mlp_t.fc1.weight", "module.blocks_ts.1.mlp_t.fc1.bias", "module.blocks_ts.1.mlp_t.fc2.weight", "module.blocks_ts.1.mlp_t.fc2.bias", "module.blocks_ts.2.norm1_s.weight", "module.blocks_ts.2.norm1_s.bias", "module.blocks_ts.2.norm1_t.weight", "module.blocks_ts.2.norm1_t.bias", "module.blocks_ts.2.attn_s.proj.weight", "module.blocks_ts.2.attn_s.proj.bias", "module.blocks_ts.2.attn_s.qkv.weight", "module.blocks_ts.2.attn_s.qkv.bias", "module.blocks_ts.2.attn_t.proj.weight", "module.blocks_ts.2.attn_t.proj.bias", "module.blocks_ts.2.attn_t.qkv.weight", "module.blocks_ts.2.attn_t.qkv.bias", "module.blocks_ts.2.norm2_s.weight", "module.blocks_ts.2.norm2_s.bias", "module.blocks_ts.2.norm2_t.weight", "module.blocks_ts.2.norm2_t.bias", "module.blocks_ts.2.mlp_s.fc1.weight", "module.blocks_ts.2.mlp_s.fc1.bias", "module.blocks_ts.2.mlp_s.fc2.weight", "module.blocks_ts.2.mlp_s.fc2.bias", "module.blocks_ts.2.mlp_t.fc1.weight", "module.blocks_ts.2.mlp_t.fc1.bias", "module.blocks_ts.2.mlp_t.fc2.weight", "module.blocks_ts.2.mlp_t.fc2.bias", "module.blocks_ts.3.norm1_s.weight", "module.blocks_ts.3.norm1_s.bias", "module.blocks_ts.3.norm1_t.weight", "module.blocks_ts.3.norm1_t.bias", "module.blocks_ts.3.attn_s.proj.weight", "module.blocks_ts.3.attn_s.proj.bias", "module.blocks_ts.3.attn_s.qkv.weight", "module.blocks_ts.3.attn_s.qkv.bias", "module.blocks_ts.3.attn_t.proj.weight", "module.blocks_ts.3.attn_t.proj.bias", "module.blocks_ts.3.attn_t.qkv.weight", "module.blocks_ts.3.attn_t.qkv.bias", "module.blocks_ts.3.norm2_s.weight", "module.blocks_ts.3.norm2_s.bias", "module.blocks_ts.3.norm2_t.weight", "module.blocks_ts.3.norm2_t.bias", "module.blocks_ts.3.mlp_s.fc1.weight", "module.blocks_ts.3.mlp_s.fc1.bias", "module.blocks_ts.3.mlp_s.fc2.weight", "module.blocks_ts.3.mlp_s.fc2.bias", "module.blocks_ts.3.mlp_t.fc1.weight", "module.blocks_ts.3.mlp_t.fc1.bias", "module.blocks_ts.3.mlp_t.fc2.weight", "module.blocks_ts.3.mlp_t.fc2.bias", "module.blocks_ts.4.norm1_s.weight", "module.blocks_ts.4.norm1_s.bias", "module.blocks_ts.4.norm1_t.weight", "module.blocks_ts.4.norm1_t.bias", "module.blocks_ts.4.attn_s.proj.weight", "module.blocks_ts.4.attn_s.proj.bias", "module.blocks_ts.4.attn_s.qkv.weight", "module.blocks_ts.4.attn_s.qkv.bias", "module.blocks_ts.4.attn_t.proj.weight", "module.blocks_ts.4.attn_t.proj.bias", "module.blocks_ts.4.attn_t.qkv.weight", "module.blocks_ts.4.attn_t.qkv.bias", "module.blocks_ts.4.norm2_s.weight", "module.blocks_ts.4.norm2_s.bias", "module.blocks_ts.4.norm2_t.weight", "module.blocks_ts.4.norm2_t.bias", "module.blocks_ts.4.mlp_s.fc1.weight", "module.blocks_ts.4.mlp_s.fc1.bias", "module.blocks_ts.4.mlp_s.fc2.weight", "module.blocks_ts.4.mlp_s.fc2.bias", "module.blocks_ts.4.mlp_t.fc1.weight", "module.blocks_ts.4.mlp_t.fc1.bias", "module.blocks_ts.4.mlp_t.fc2.weight", "module.blocks_ts.4.mlp_t.fc2.bias", "module.norm.weight", "module.norm.bias", "module.pre_logits.fc.weight", "module.pre_logits.fc.bias", "module.head.weight", "module.head.bias", "module.ts_attn.0.weight", "module.ts_attn.0.bias", "module.ts_attn.1.weight", "module.ts_attn.1.bias", "module.ts_attn.2.weight", "module.ts_attn.2.bias", "module.ts_attn.3.weight", "module.ts_attn.3.bias", "module.ts_attn.4.weight", "module.ts_attn.4.bias". 
```

</details>

I guess there is a mismatch between the checkpoint and the configuration file (and maybe code?). I am sure that I downloaded the checkpoint from the link in the `inference.MD`. Could you please double-check?

Note: I tried to load the checkpoint with all other configuration files in `/configs/pose3d`, none worked

<details>
  <summary>Here is the code I am running</summary>

```
import os
import argparse
import torch
import torch.nn as nn
import os, sys
sys.path.append(os.getcwd())
from lib.utils.tools import *
from lib.utils.learning import *


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str, default="configs/pose3d/MB_ft_h36m_global_lite.yaml",
                        help="Path to the config file.")
    parser.add_argument('-e', '--evaluate', default='checkpoint/pose3d/FT_MB_lite_MB_ft_h36m_global_lite/best_epoch.bin',
                        type=str, metavar='FILENAME', help='checkpoint to evaluate (file name)')
    # parser.add_argument('-j', '--json_path', type=str, help='alphapose detection result json path')
    # parser.add_argument('-v', '--vid_path', type=str, help='video path')
    parser.add_argument('-o', '--out_path', type=str, help='output path')
    parser.add_argument('--pixel', action='store_true', help='align with pixle coordinates')
    parser.add_argument('--focus', type=int, default=None, help='target person id')
    parser.add_argument('--clip_len', type=int, default=243, help='clip length for network input')
    opts = parser.parse_args()
    return opts


opts = parse_args()
args = get_config(opts.config)

model_backbone = load_backbone(args)

print('Loading checkpoint', opts.evaluate)
checkpoint = torch.load(opts.evaluate, map_location="cpu")
model_backbone.load_state_dict(checkpoint['model_pos'], strict=True)
```

</details>

**Comment by Walter0807** [comment]
Thanks for your interest in our work! This post might be useful: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/2

**Comment by H4dr1en** [comment]
Indeed, Thanks for the fast answer!
