### ISSUE TITLE
An error in infer_wild.py

### ISSUE THREAD

**Issue by Ared521** [Walter0807/MotionBERT#40]
Hello, I have met a difficulty and do not know how to solve it. My error is as follows. May I ask what happened and how to correct it? I'm using a Windows10 computer. Thank you so much!!

(motionbert) F:\DeepLearning\MotionBERT\MotionBERT-main&gt; python infer_wild.py --vid_path video/me.mp4 --json_path video_json/vis_me.mp4.json --out_path output

Loading checkpoint checkpoint/pose3d/FT_MB_lite_MB_ft_h36m_global_lite/best_epoch.bin

0% |                                                                                        | 0/2 [00:00&lt;?, ?it/s]L

oading checkpoint checkpoint/pose3d/FT_MB_lite_MB_ft_h36m_global_lite/best_epoch.bin

0% |                                                                                        | 0/2 [00:00&lt;?, ?it/s]

Traceback (most recent call last):

File "&lt; string&gt;" , line 1, in &lt; module&gt;

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\spawn.py", line 116, in spawn_main

exitcode = _main(fd, parent_sentinel)

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\spawn.py", line 125, in _main

prepare(preparation_data)

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\spawn.py", line 236, in prepare

_fixup_main_from_path(data['init_main_from_path'])

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path

main_content = runpy.run_path(main_path,

File "F:\Software\Anaconda\envs\motionbert\lib\runpy.py", line 289, in run_path

return _run_module_code(code, init_globals, run_name,

File "F:\Software\Anaconda\envs\motionbert\lib\runpy.py", line 96, in _run_module_code

_run_code(code, mod_globals, init_globals,

File "F:\Software\Anaconda\envs\motionbert\lib\runpy.py", line 86, in _run_code

exec(code, run_globals)

File "F:\DeepLearning\MotionBERT\MotionBERT-main\infer_wild.py", line 70, in &lt; module&gt;

for batch_input in tqdm(test_loader):

File "F:\Software\Anaconda\envs\motionbert\lib\site-packages\tqdm\std.py", line 1178, in __iter__

for obj in iterable:

File "F:\Software\Anaconda\envs\motionbert\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__

self._iterator = self._get_iterator()

File "F:\Software\Anaconda\envs\motionbert\lib\site-packages\torch\utils\data\dataloader.py", line 390, in _get_iterator

return _MultiProcessingDataLoaderIter(self)

File "F:\Software\Anaconda\envs\motionbert\lib\site-packages\torch\utils\data\dataloader.py", line 1077, in __init__

w.start()

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\process.py", line 121, in start

self._popen = self._Popen(self)

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\context.py", line 224, in _Popen

return _default_context.get_context().Process._Popen(process_obj)

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\context.py", line 336, in _Popen

return Popen(process_obj)

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__

prep_data = spawn.get_preparation_data(process_obj._name)

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\spawn.py", line 154, in get_preparation_data

_check_not_importing_main()

File "F:\Software\Anaconda\envs\motionbert\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main

raise RuntimeError('''

RuntimeError:

An attempt has been made to start a new process before the

current process has finished its bootstrapping phase.

This probably means that you are not using fork to start your

child processes and you have forgotten to use the proper idiom

in the main module:

if __name__ == '__main__':

freeze_support()

...

The "freeze_support()" line can be omitted if the program

is not going to be frozen to produce an executable.

**Comment by Ared521** [comment]
Now, I know, because I only have one GPU, num_worker I should set to 0, by the way, prefetch_factor and persistent_workers, what do those two parameters do? If I set num_worker = 0, what should these two parameters be set to?

**Comment by Walter0807** [comment]
Please refer to Pytorch documentation to find the proper dataloader configs for your setting.

**Comment by jyunChang** [comment]
same error, have you done?
